class Categories {
  static getCategories(): { [key: string]: string } {
    return {
      'Primarily Teen Cast': 'Cast-Main Cast',
      'Primarily Child Cast': 'Cast-Main Cast',
      'Male Protagonist': 'Cast-Main Cast',
      'Primarily Female Cast': 'Cast-Main Cast',
      'Female Protagonist': 'Cast-Main Cast',
      'Primarily Male Cast': 'Cast-Main Cast',
      'Primarily Adult Cast': 'Cast-Main Cast',
      'Anti-Hero': 'Cast-Main Cast',
      'Ensemble Cast': 'Cast-Main Cast',
      'Office Lady': 'Cast-Traits',
      'Ninja': 'Cast-Traits',
      'Kemonomimi': 'Cast-Traits',
      'Transgender': 'Cast-Traits',
      'VTuber': 'Cast-Traits',
      'Gyaru': 'Cast-Traits',
      'Monster Girl': 'Cast-Traits',
      'Vikings': 'Cast-Traits',
      'Amnesia': 'Cast-Traits',
      'Nekomimi': 'Cast-Traits',
      'Artificial Intelligence': 'Cast-Traits',
      'Ghost': 'Cast-Traits',
      'Yandere': 'Cast-Traits',
      'Idol': 'Cast-Traits',
      'Mermaid': 'Cast-Traits',
      'Elf': 'Cast-Traits',
      'Goblin': 'Cast-Traits',
      'Pirates': 'Cast-Traits',
      'Hikikomori': 'Cast-Traits',
      'Succubus': 'Cast-Traits',
      'Kuudere': 'Cast-Traits',
      'Teacher': 'Cast-Traits',
      'Femboy': 'Cast-Traits',
      'Tanned Skin': 'Cast-Traits',
      'Twins': 'Cast-Traits',
      'Asexual': 'Cast-Traits',
      'Demons': 'Cast-Traits',
      'Shrine Maiden': 'Cast-Traits',
      'Anthropomorphism': 'Cast-Traits',
      'Disability': 'Cast-Traits',
      'Skeleton': 'Cast-Traits',
      'Clone': 'Cast-Traits',
      'Tsundere': 'Cast-Traits',
      'Maids': 'Cast-Traits',
      'Tomboy': 'Cast-Traits',
      'Vampire': 'Cast-Traits',
      'Delinquents': 'Cast-Traits',
      'Ojou-sama': 'Cast-Traits',
      'Chuunibyou': 'Cast-Traits',
      'Centaur': 'Cast-Traits',
      'Cosplay': 'Cast-Traits',
      'Witch': 'Cast-Traits',
      'Butler': 'Cast-Traits',
      'Robots': 'Cast-Traits',
      'Dinosaurs': 'Cast-Traits',
      'Nun': 'Cast-Traits',
      'Detective': 'Cast-Traits',
      'Oiran': 'Cast-Traits',
      'Monster Boy': 'Cast-Traits',
      'Dullahan': 'Cast-Traits',
      'Age Regression': 'Cast-Traits',
      'Nudity': 'Cast-Traits',
      'Villainess': 'Cast-Traits',
      'Dragons': 'Cast-Traits',
      'Angels': 'Cast-Traits',
      'Aliens': 'Cast-Traits',
      'Zombie': 'Cast-Traits',
      'Samurai': 'Cast-Traits',
      'Gods': 'Cast-Traits',
      'Agender': 'Cast-Traits',
      'Fairy': 'Cast-Traits',
      'Crossdressing': 'Cast-Traits',
      'Werewolf': 'Cast-Traits',
      'Orphan': 'Cast-Traits',
      'Dissociative Identities': 'Cast-Traits',
      'Homeless': 'Cast-Traits',
      'Cyborg': 'Cast-Traits',
      'Chimera': 'Cast-Traits',
      'Shoujo': 'Demographic',
      'Josei': 'Demographic',
      'Kids': 'Demographic',
      'Shounen': 'Demographic',
      'Seinen': 'Demographic',
      'Circus': 'Setting-Scene',
      'Foreign': 'Setting-Scene',
      'Rural': 'Setting-Scene',
      'Outdoor': 'Setting-Scene',
      'Language Barrier': 'Setting-Scene',
      'College': 'Setting-Scene',
      'Urban': 'Setting-Scene',
      'School': 'Setting-Scene',
      'Work': 'Setting-Scene',
      'School Club': 'Setting-Scene',
      'Prison': 'Setting-Scene',
      'Dungeon': 'Setting-Scene',
      'Bar': 'Setting-Scene',
      'Desert': 'Setting-Scene',
      'Achronological Order': 'Setting-Time',
      'Time Skip': 'Setting-Time',
      'Anachronism': 'Setting-Time',
      'Dystopian': 'Setting-Time',
      'Historical': 'Setting-Time',
      'Alternate Universe': 'Setting-Universe',
      'Space': 'Setting-Universe',
      'Augmented Reality': 'Setting-Universe',
      'Afterlife': 'Setting-Universe',
      'Virtual World': 'Setting-Universe',
      'Omegaverse': 'Setting-Universe',
      'Post-Apocalyptic': 'Setting-Universe',
      'Urban Fantasy': 'Setting-Universe',
      'Defloration': 'Sexual Content',
      'Public Sex': 'Sexual Content',
      'Voyeur': 'Sexual Content',
      'Ashikoki': 'Sexual Content',
      'Femdom': 'Sexual Content',
      'Zoophilia': 'Sexual Content',
      'Sadism': 'Sexual Content',
      'MILF': 'Sexual Content',
      'Bondage': 'Sexual Content',
      'Handjob': 'Sexual Content',
      'Prostitution': 'Sexual Content',
      'Futanari': 'Sexual Content',
      'Scat': 'Sexual Content',
      'Masturbation': 'Sexual Content',
      'Facial': 'Sexual Content',
      'Netori': 'Sexual Content',
      'Amputation': 'Sexual Content',
      'Sweat': 'Sexual Content',
      'Irrumatio': 'Sexual Content',
      'DILF': 'Sexual Content',
      'Rape': 'Sexual Content',
      'Watersports': 'Sexual Content',
      'Virginity': 'Sexual Content',
      'Lactation': 'Sexual Content',
      'Sumata': 'Sexual Content',
      'Hypersexuality': 'Sexual Content',
      'Exhibitionism': 'Sexual Content',
      'Nakadashi': 'Sexual Content',
      'Cunnilingus': 'Sexual Content',
      'Vore': 'Sexual Content',
      'Rimjob': 'Sexual Content',
      'Blackmail': 'Sexual Content',
      'Large Breasts': 'Sexual Content',
      'Sex Toys': 'Sexual Content',
      'Asphyxiation': 'Sexual Content',
      'Inseki': 'Sexual Content',
      'Scissoring': 'Sexual Content',
      'Deepthroat': 'Sexual Content',
      'Armpits': 'Sexual Content',
      'Fellatio': 'Sexual Content',
      'Squirting': 'Sexual Content',
      'Netorare': 'Sexual Content',
      'Cumflation': 'Sexual Content',
      'Flat Chest': 'Sexual Content',
      'Masochism': 'Sexual Content',
      'Tentacles': 'Sexual Content',
      'Boobjob': 'Sexual Content',
      'Human Pet': 'Sexual Content',
      'Ahegao': 'Sexual Content',
      'Incest': 'Sexual Content',
      'Pregnant': 'Sexual Content',
      'Threesome': 'Sexual Content',
      'Netorase': 'Sexual Content',
      'Feet': 'Sexual Content',
      'Group Sex': 'Sexual Content',
      'Anal Sex': 'Sexual Content',
      'Rotoscoping': 'Technical',
      'Advertisement': 'Technical',
      'POV': 'Technical',
      'Episodic': 'Technical',
      'CGI': 'Technical',
      'Full CGI': 'Technical',
      'Puppetry': 'Technical',
      '4-koma': 'Technical',
      'No Dialogue': 'Technical',
      'Full Color': 'Technical',
      'Achromatic': 'Technical',
      'Stop Motion': 'Technical',
      'Flash': 'Technical',
      'Non-fiction': 'Technical',
      'Anthology': 'Technical',
      'Battle Royale': 'Theme-Action',
      'Martial Arts': 'Theme-Action',
      'Espionage': 'Theme-Action',
      'Guns': 'Theme-Action',
      'Swordplay': 'Theme-Action',
      'Archery': 'Theme-Action',
      'Spearplay': 'Theme-Action',
      'Fugitive': 'Theme-Action',
      'Food': 'Theme-Arts',
      'Calligraphy': 'Theme-Arts',
      'Photography': 'Theme-Arts',
      'Writing': 'Theme-Arts',
      'Acting': 'Theme-Arts',
      'Drawing': 'Theme-Arts',
      'Classic Literature': 'Theme-Arts',
      'Fashion': 'Theme-Arts',
      'Makeup': 'Theme-Arts',
      'Rakugo': 'Theme-Arts',
      'Band': 'Theme-Arts-Music',
      'Dancing': 'Theme-Arts-Music',
      'Musical': 'Theme-Arts-Music',
      'Surreal Comedy': 'Theme-Comedy',
      'Parody': 'Theme-Comedy',
      'Slapstick': 'Theme-Comedy',
      'Satire': 'Theme-Comedy',
      'Suicide': 'Theme-Drama',
      'Tragedy': 'Theme-Drama',
      'Revenge': 'Theme-Drama',
      'Conspiracy': 'Theme-Drama',
      'Rehabilitation': 'Theme-Drama',
      'Coming of Age': 'Theme-Drama',
      'Bullying': 'Theme-Drama',
      'Fairy Tale': 'Theme-Fantasy',
      'Kaiju': 'Theme-Fantasy',
      'Superhero': 'Theme-Fantasy',
      'Alchemy': 'Theme-Fantasy',
      'Isekai': 'Theme-Fantasy',
      'Cultivation': 'Theme-Fantasy',
      'Wuxia': 'Theme-Fantasy',
      'Super Power': 'Theme-Fantasy',
      'Body Swapping': 'Theme-Fantasy',
      'Youkai': 'Theme-Fantasy',
      'Mythology': 'Theme-Fantasy',
      'Steampunk': 'Theme-Fantasy',
      'Shapeshifting': 'Theme-Fantasy',
      'Necromancy': 'Theme-Fantasy',
      'Magic': 'Theme-Fantasy',
      'Henshin': 'Theme-Fantasy',
      'E-Sports': 'Theme-Game',
      'Video Games': 'Theme-Game',
      'Shogi': 'Theme-Game-Card & Board Game',
      'Mahjong': 'Theme-Game-Card & Board Game',
      'Card Battle': 'Theme-Game-Card & Board Game',
      'Go': 'Theme-Game-Card & Board Game',
      'Poker': 'Theme-Game-Card & Board Game',
      'Karuta': 'Theme-Game-Card & Board Game',
      'Badminton': 'Theme-Game-Sport',
      'Table Tennis': 'Theme-Game-Sport',
      'Wrestling': 'Theme-Game-Sport',
      'Airsoft': 'Theme-Game-Sport',
      'Athletics': 'Theme-Game-Sport',
      'Cycling': 'Theme-Game-Sport',
      'Lacrosse': 'Theme-Game-Sport',
      'Swimming': 'Theme-Game-Sport',
      'Cheerleading': 'Theme-Game-Sport',
      'Boxing': 'Theme-Game-Sport',
      'Golf': 'Theme-Game-Sport',
      'Basketball': 'Theme-Game-Sport',
      'Fishing': 'Theme-Game-Sport',
      'Football': 'Theme-Game-Sport',
      'Parkour': 'Theme-Game-Sport',
      'Skateboarding': 'Theme-Game-Sport',
      'Handball': 'Theme-Game-Sport',
      'Rugby': 'Theme-Game-Sport',
      'Fencing': 'Theme-Game-Sport',
      'Judo': 'Theme-Game-Sport',
      'Ice Skating': 'Theme-Game-Sport',
      'Surfing': 'Theme-Game-Sport',
      'Baseball': 'Theme-Game-Sport',
      'American Football': 'Theme-Game-Sport',
      'Fitness': 'Theme-Game-Sport',
      'Scuba Diving': 'Theme-Game-Sport',
      'Sumo': 'Theme-Game-Sport',
      'Volleyball': 'Theme-Game-Sport',
      'Tennis': 'Theme-Game-Sport',
      'Autobiographical': 'Theme-Other',
      'Meta': 'Theme-Other',
      'Cosmic Horror': 'Theme-Other',
      'Marriage': 'Theme-Other',
      'Chibi': 'Theme-Other',
      'Crossover': 'Theme-Other',
      'Slavery': 'Theme-Other',
      'Terrorism': 'Theme-Other',
      'Religion': 'Theme-Other',
      'Found Family': 'Theme-Other',
      'Ero Guro': 'Theme-Other',
      'Medicine': 'Theme-Other',
      'Reincarnation': 'Theme-Other',
      'Economics': 'Theme-Other',
      'Biographical': 'Theme-Other',
      'Philosophy': 'Theme-Other',
      'Gambling': 'Theme-Other',
      'Gender Bending': 'Theme-Other',
      'Pandemic': 'Theme-Other',
      'War': 'Theme-Other',
      'Memory Manipulation': 'Theme-Other',
      'LGBTQ+ Themes': 'Theme-Other',
      'Death Game': 'Theme-Other',
      'Noir': 'Theme-Other',
      'Travel': 'Theme-Other',
      'Body Horror': 'Theme-Other',
      'Otaku Culture': 'Theme-Other',
      'Gore': 'Theme-Other',
      'Survival': 'Theme-Other',
      'Crime': 'Theme-Other',
      'Drugs': 'Theme-Other',
      'Software Development': 'Theme-Other',
      'Torture': 'Theme-Other',
      'Educational': 'Theme-Other',
      'Denpa': 'Theme-Other',
      'Astronomy': 'Theme-Other',
      'Cannibalism': 'Theme-Other',
      'Adoption': 'Theme-Other',
      'Environmental': 'Theme-Other',
      'Animals': 'Theme-Other',
      'Lost Civilization': 'Theme-Other',
      'Politics': 'Theme-Other',
      'Firefighters': 'Theme-Other-Organisations',
      'Yakuza': 'Theme-Other-Organisations',
      'Military': 'Theme-Other-Organisations',
      'Assassins': 'Theme-Other-Organisations',
      'Triads': 'Theme-Other-Organisations',
      'Gangs': 'Theme-Other-Organisations',
      'Mafia': 'Theme-Other-Organisations',
      'Cult': 'Theme-Other-Organisations',
      'Police': 'Theme-Other-Organisations',
      'Trains': 'Theme-Other-Vehicle',
      'Tanks': 'Theme-Other-Vehicle',
      'Motorcycles': 'Theme-Other-Vehicle',
      'Cars': 'Theme-Other-Vehicle',
      'Ships': 'Theme-Other-Vehicle',
      'Mopeds': 'Theme-Other-Vehicle',
      'Aviation': 'Theme-Other-Vehicle',
      'Love Triangle': 'Theme-Romance',
      'Age Gap': 'Theme-Romance',
      'Teens\' Love': 'Theme-Romance',
      'Yuri': 'Theme-Romance',
      'Heterosexual': 'Theme-Romance',
      'Bisexual': 'Theme-Romance',
      'Boys\' Love': 'Theme-Romance',
      'Mixed Gender Harem': 'Theme-Romance',
      'Male Harem': 'Theme-Romance',
      'Female Harem': 'Theme-Romance',
      'Time Manipulation': 'Theme-Sci-Fi',
      'Cyberpunk': 'Theme-Sci-Fi',
      'Space Opera': 'Theme-Sci-Fi',
      'Tokusatsu': 'Theme-Sci-Fi',
      'Super Robot': 'Theme-Sci-Fi-Mecha',
      'Real Robot': 'Theme-Sci-Fi-Mecha',
      'Agriculture': 'Theme-Slice of Life',
      'Family Life': 'Theme-Slice of Life',
      'Cute Boys Doing Cute Things': 'Theme-Slice of Life',
      'Cute Girls Doing Cute Things': 'Theme-Slice of Life',
      'Iyashikei': 'Theme-Slice of Life',
    };
  }
}

export default Categories;
